[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "ntnda-qt-viewer"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
description = "ntnda-qt-viewer"
dependencies = [
    "p4p>=4.2.2",
    "pyqtgraph>=0.14.0",
    "qtpy>=2.4.3",
]

dynamic = ["version"]
license.file = "LICENSE"
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
pyside6 = ["PySide6"]
pyqt6 = ["PyQt6"]

[project.scripts]
ntnda-qt-viewer = "ntnda_qt_viewer.__main__:main"

[project.urls]
GitHub = "https://github.com/NSLS2/ntnda-qt-viewer"

[[project.authors]]
email = "jwlodek@bnl.gov"
name = "Jakub Wlodek"

[dependency-groups]
dev = [
    "ty",
    "copier",
    "pipdeptree",
    "pre-commit",
    "pyright",
    "pytest",
    "pytest-cov",
    "ruff",
    "tox-direct",
    "types-mock",
    "import-linter",
]


[tool.setuptools_scm]
version_file = "src/ntnda_qt_viewer/_version.py"

[tool.pyright]
typeCheckingMode = "standard"
reportMissingImports = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
addopts = """
    --tb=native -vv
    """
filterwarnings = "error"
testpaths = "docs src tests"

[tool.coverage.run]
data_file = "/tmp/ntnda_qt_viewer.coverage"

[tool.coverage.paths]
source = ["src", "**/site-packages/"]

[tool.tox]
legacy_tox_ini = """
[tox]
skipsdist=True

[testenv:{pre-commit,type-checking,tests}]
direct = True
passenv = *
allowlist_externals =
    pytest
    pre-commit
    pyright
commands =
    pre-commit: pre-commit run --all-files --show-diff-on-failure {posargs}
    type-checking: pyright src tests {posargs}
    tests: pytest --cov=ntnda_qt_viewer --cov-report term --cov-report xml:cov.xml {posargs}
"""

[tool.ruff]
src = ["src", "tests"]
line-length = 88
lint.select = [
    "B",
    "C4",
    "E",
    "F",
    "W",
    "I",
    "UP",
    "SLF",
]
exclude = [
    "src/ntnda_qt_viewer/_version.py",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["SLF001"]

[tool.importlinter]
root_package = "ntnda_qt_viewer"
