name: Publish Release to PyPI
permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          uv build

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Install produced wheel
        run: |
          uv pip install "$(ls dist/*.whl)[pyside6]" --system

      - name: Verify installation
        run: |
          ntnda-qt-viewer --version
